language: go
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

go:
  - 1.9

go_import_path: github.com/uber-go/dosa

cache:
  directories:
    - vendor

install:
  - make vendor
  - pip install --user cql PyYAML six
  - git clone --depth 1 https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get github.com/golang/mock/mockgen
  - go get golang.org/x/lint

script:
  - make lint
  - make test

after_success:
  - make coveralls

services:
  - redis-server
